### ISSUE TITLE
Custom delimiter for "csv" output style

### ISSUE THREAD

**Issue by NaveenSrikanth** [scgray/jsqsh#12]
The tutorial which you have given is very helpful.

I have been using bigsql from past 3 months , 

The issue is I am not able to export my data from jsqsh in to pipe delimiter or any other character I can export only to csv file . 

I passing in jasqsh like "-i ${XXX}/records_retrieve.sql  -o /home/ccc/xxx/${TABLE}_datafile.csv"

Now I wanted the file to be delimieted with thron character or pipeline please suggest how can I do it . I am not getting proper answer for this . Please help

**Comment by scgray** [comment]
Right now the CSV formatter is, as the name implies, strictly comma separated values.  I can see if I can make some modifications to allow the delimiter to be configurable though. 

Thanks for the feedback and suggestion.
