### ISSUE TITLE
Insert a japanese charecters  into hadoop table using jsqsh garbles the charecters

### ISSUE THREAD

**Issue by shankaribm** [scgray/jsqsh#49]
Hi Team,

I have tried to create a hadoop table using the following definition from IBM BigInsights BigSQL

CREATE HADOOP TABLE IF NOT EXISTS  nap.empdet1234 (  
 COMM       VARCHAR(3 CODEUNITS32)
 STORED AS ORC tblproperties('orc.compress' ='ZLIB',  
'orc.compress.size' ='262144',
'orc.row.index.stride' = '10000',
 'orc.create.index' ='true', 'orc.stripe.size' ='67108864');

Create a file insert.sql
INSERT INTO nap.mytable VALUES ('代');

Now try to insert this data using jsqsh with the following command 
jsqsh skt -e -i insert.sql
INSERT INTO nap.empdet1234 VALUES ('代');
0 rows affected (total: 1.16s)

[skt@ldinsights01 work]$ jsqsh biadmin
JSqsh Release 2.1.0.4, Copyright (C) 2007-2016, Scott C. Gray
Type \help for available help topics. Using JLine.
[ldinsights01.da.dnp.co.jp][skt] 1> SELECT * FROM nap.empdet1234;

+-------------+
 | COMM |
+-------+
| 1a≫￡2 |
+-------+
1 row in results(first row: 4.83s; total: 4.94s)

Looking at the encoding used and dump of octal 

bigsql@bivm:~/dnp1> file -bi data.sql
text/plain charset=utf-8
bigsql@bivm:~/dnp1> od -c -Ax data.sql
000000   i   n   s   e   r   t       i   n   t   o           d   n   p
000010   .   e   m   p   d   e   t   1   2   3   4       v   a   l   u
000020   e   s   (   '   1 344 273 243   2   '   )   ;  \n
00002d
bigsql@bivm:~/dnp1> this should be stored in utf8 hex value which is E4 BB A3

Refer to the following  link for the encodings of this special character used 
http://graphemica.com/%E4%BB%A3

Alternatively using the following works fine 

create a file data.txt with following entries and load the same into hadoop
20 emp1
40 emp2
15 emp3
35 emp5

This this file into hadoop using hadoop dfs put data.txt  /tmp/hl folder 

bivm:~> db2 "create hadoop table dnp.empdet123( enum integer,
ename varchar(10) ) ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n' location '/tmp/hl'";
DB20000I  The SQL command completed successfully.
bigsql@bivm:~> db2 "select * from dnp.empdet123";

ENUM        ENAME
----------- ----------
         20 emp1
         40 emp2
         15 emp3
         35 emp5

  4 record(s) selected.

bigsql@bivm:~> db2 "create hadoop table dnp.empdet1234( evarch varchar(20))";
DB20000I  The SQL command completed successfully.

Login into jsqsh

bigsql@bivm:~>cd /opt/ibm/biginsights/jsqsh/bin/
bigsql@bivm:/opt/ibm/biginsights/jsqsh/bin> ls
jsqsh  jsqsh.bat
bigsql@bivm:/opt/ibm/biginsights/jsqsh/bin> ./jsqsh bigsql
JSqsh Release 2.1.0.4, Copyright (C) 2007-2016, Scott C. Gray
Type \help for available help topics. Using JLine.

[bivm.ibm.com][bigsql] 1>  insert into dnp.empdet1234  select concat(ename, '代')  from DNP.EMPDET123;
0 rows affected (total: 4.17s)
[bivm.ibm.com][bigsql] 1> select * from dnp.empdet1234;
+--------+
| EVARCH |
+--------+
| emp1 代 |
| emp2 代 |
| emp3 代 |
| emp5代  |
+--------+
4 rows in results(first row: 0.18s; total: 0.18s) 

Is it possible that jsqsh skt -e -i <insert.sql > work fine so an insert can be made directly without the 2 step process...

**Comment by shankaribm** [comment]
All the above text is valid, don't know why some part of the text was striked offf

**Comment by scgray** [comment]
The strikeout was because GitHub uses "markdown" to let you format your text using certain patterns (see https://guides.github.com/features/mastering-markdown/). 

The behavior with -i is interesting, and I have reproduced it using Derby. I'll take a look and see what might be going on
