### ISSUE TITLE
Option to set exit threshold in batch processing, similar to $thresh_exit in sqsh

### ISSUE THREAD

**Issue by ljagadeesh06** [scgray/jsqsh#62]
sqsh is having an option to continue executing current batch statements till the exit count reaches a specified threshold. This threshold can be set with $thresh_exit variable. Similar feature is needed in jsqsh

**Comment by scgray** [comment]
Hi @ljagadeesh06 there is a feature pretty close to what you are talking about via the `${exit_on}` variable (see https://github.com/scgray/jsqsh/wiki/exit_on).  The only difference is that it doesn't support the ability to specify a number of failures -- it will exit on the first failure.  Would this work for you?

**Comment by ljagadeesh06** [comment]
Hi @scgray, thanks for your reply. I tried that option by setting exit_on=none. It's able to continue executing other statements in an input file. But this won't continue within a stored procedure. It's weird to do that in fact. since sqsh is doing that we are using in our project. Now we need similar feature in jsqsh also. 
Other than this, jsqsh is identical to sqsh and I am able to replace all my existing code to use jsqsh. Thanks for this awesome tool

**Comment by scgray** [comment]
I'm not sure I follow.  With `exit_on=none` JSqsh should never exit on the failure of a statement (stored procedure or otherwise).  With `exit_on=any` or `exit_on=go` it should exit on the first error it receives.  Are you saying that it continues to the end of a stored procedure even if the first statement in that procedure fails?

**Comment by ljagadeesh06** [comment]
Somehow sqsh is able to read resultsets from storedprocedure even after an exception is thrown from the procedure. 
In the output, it displays the error message and after that the next result set will be displayed

May be something like this

**thresh_display=22, thresh_fail=0, thresh_exit=3**
This behaves the same as the previous example, with the exception that all error messages will be suppressed from being displayed. This is particularly useful if you just care about the exit value more than the actual error.

**Comment by ljagadeesh06** [comment]
Looks like it's a freetds driver thing. I am sorry for false alarm. I am closing this issue.
